[Ideas]
Vim setup
How the modern web is bloated
Chip 8 emulator in rust
Philosophy - Should the gov put rules in social media
Wal theme for spotify
Nyc photoshoot

[Doing]


[Done]
Custom keyboard
Desktop Setup
how this site was made

[Bad-Idea]

